config/routes.rb
Rails.application.routes.draw do
  devise_for :members, path: ''

  devise_scope :member do
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_out', to: 'devise/sessions#destroy'

    unauthenticated :member do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  authenticate :member do
    root to: 'members#index', as: :authenticated_root

    resources :members
    resources :teams
    resources :service_apps, only: [:index, :create, :destroy]
  end

  namespace :api do
    namespace :v1 do
      post 'sign_in', to: 'sessions#create'
      post 'sign_out', to: 'sessions#destroy'

      resources :members, only: [:index, :show] 
      get 'members/actions/showByUsername', to: 'members#showByUsername'

      resources :reservations, only: [:index, :create, :show]
      get 'reservations/actions/showHistoryByUsername', to: 'reservations#showHistoryByUsername'
      get 'reservations/actions/showCurrentByUsername', to: 'reservations#showCurrentByUsername'
    end
  end
end

app/models/member.rb
class Member < ApplicationRecord
  before_create :generate_token

  devise :database_authenticatable

  validates :role,
            :email,
            :major,
            :status,
            :generation,
            :first_name,
            :start_date,
            :github_username,
            :fathers_last_name,
            :mothers_last_name,
            presence: true

  validates :github_username, uniqueness: true

  has_many :team_members
  has_many :teams, through: :team_members
  has_many :event_members
  has_many :events, through: :event_members
  has_many :arrangement_members
  has_many :arrangements, through: :arrangement_members
  has_many :reservations

  scope :sorted_by_role, -> { order('role') }
  scope :sorted_by_major, -> { order('major') }
  scope :sorted_by_status, -> { order('status') }
  scope :sorted_by_generation, -> { order('generation') }

  enum role: {
    software: 0,
    marketing: 1,
    mechanics: 2,
    electronics: 3,
  }

  enum status: {
    active: 0,
    neutral: 1,
    conditioned: 2,
    inactive: 3,
    affiliated: 4,
  }

  enum major: {
    ITC: 0,
    ISD: 1,
    IMT: 2,
    BAA: 3,
    ITI: 4,
    IID: 5,
    IM: 6,
    LIN: 7,
    LEC: 8,
    ICT: 9,
    IE: 10,
    IRS: 11,
    BGB: 12,
    INA: 13,
    ITD: 14,
    BCT: 15,
    LAD: 16,
  }

  def full_name
    "#{self.first_name} #{self.fathers_last_name} #{self.mothers_last_name}"
  end

  private

  def generate_token
    begin
      self.token = SecureRandom.uuid
    end while self.class.exists?(token: token)
  end
end

app/controllers/api/v1/members_controller.rb
class Api::V1::MembersController < Api::V1::BaseController
  def index
    params[:sort_by] ||= :generation

    @members = {
      role: Member.all.sorted_by_role,
      major: Member.all.sorted_by_major,
      status: Member.all.sorted_by_status,
      generation: Member.all.sorted_by_generation,
    }.fetch(params[:sort_by]&.to_sym)

    render json: @members
  end

  def show
    @member = Member.find(params[:id])
    
    render json: @member
  end
  
  def showByUsername
    @member = Member.find_by(username: params[:username])
    
    render json: @member
  end
  
end

app/controllers/members_controller.rb
class MembersController < BaseController
  def index
    params[:sort_by] ||= :generation

    @members = {
      role: Member.all.sorted_by_role,
      major: Member.all.sorted_by_major,
      status: Member.all.sorted_by_status,
      generation: Member.all.sorted_by_generation,
    }.fetch(params[:sort_by]&.to_sym)
  end

  def show
    @member = Member.find(params[:id])
  end

  def new
    @member = Member.new
  end

  def create
    @member = Member.new(member_params)

    if @member.save
      redirect_to @member
    else
      flash[:error] = t('messages.errors.could_not_save_member')
      redirect_to new_member_path
    end
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])

    if @member.update(member_params)
      redirect_to @member
    else
      flash[:error] = t('messages.errors.could_not_save_member')
      redirect_to edit_member_path(params[:id])
    end
  end

  def destroy
    @member = Member.find(params[:id])
    @member.destroy

    redirect_to members_path
  end

  private

  def member_params
    params.require(:member).permit(
      :first_name,
      :fathers_last_name,
      :mothers_last_name,
      :email,
      :major,
      :avatar,
      :github_username,
      :github_url,
      :linkedin_username,
      :linkedin_url,
      :resume_url,
      :status,
      :role,
      :description,
      :start_date,
      :end_date,
      :generation,
      :username
    )
  end
end

app/helpers/api/v1/members_helper.rb
module Api::V1::MembersHelper
end

app/helpers/members_helper.rb
module MembersHelper
  def role_options
    Member.roles.keys.map do |role|
      [I18n.t("options.members_role.#{role}"), role]
    end
  end

  def major_options
    Member.majors.keys
  end

  def status_options
    Member.statuses.keys.map do |status|
      [I18n.t("options.members_status.#{status}"), status]
    end
  end

  def role_badge(role)
    case role
    when 'software'
      badge = '<span class="badge badge-info">Software</span>'
    when 'marketing'
      badge = '<span class="badge badge-success">Mercadotecnia</span>'
    when 'mechanics'
      badge = '<span class="badge badge-warning">Mecánica</span>'
    when 'electronics'
      badge = '<span class="badge badge-secondary">Electrónica</span>'
    end
    badge.html_safe
  end

  def status_icon(status)
    case status
    when 'active'
      fa_icon 'circle', class: 'text-success mr-2', style: 'font-size: 0.6rem; vertical-align: middle;'
    when 'neutral'
      fa_icon 'circle', class: 'text-info mr-2', style: 'font-size: 0.6rem; vertical-align: middle;'
    when 'conditioned'
      fa_icon 'circle', class: 'text-danger mr-2', style: 'font-size: 0.6rem; vertical-align: middle;'
    when 'inactive'
      fa_icon 'circle', class: 'text-secondary mr-2', style: 'font-size: 0.6rem; vertical-align: middle;'
    when 'affiliated'
      fa_icon 'circle', class: 'text-warning mr-2', style: 'font-size: 0.6rem; vertical-align: middle;'
    end
  end
end

app/views/members/_contact_info_form.html.slim
#contact_info_form.card.not-first-card
  .card-header
    = fa_icon 'address-book fw', class: 'mr-2'
    = t('.section_title_contact')
  .card-body
    .row.justify-content-center
      .col-md-12
        .form-group.row
          = f.label :email, t('.label_email'), class: 'col-sm-3 col-form-label'
          .col-sm-9
            = f.email_field :email, class: 'form-control', required: true
        .form-group.row
          = f.label :github_username, t('.label_github_username'), class: 'col-sm-3 col-form-label'
          .col-sm-9
            = f.text_field :github_username, class: 'form-control', required: true
        .form-group.row
          = f.label :linkedin_username, t('.label_linkedin_username'), class: 'col-sm-3 col-form-label'
          .col-sm-9
            = f.text_field :linkedin_username, class: 'form-control'
        .form-group.row
          = f.label :description, t('.label_description'), class: 'col-sm-3 col-form-label'
          .col-sm-9
            = f.text_area :description, class: 'form-control', rows: 3

app/views/members/_member.html.slim
li.list-group-item.single-member
  .row
    .col
      .d-block
        = status_icon(member.status)
        = member.full_name
      = role_badge(member.role)
    .col-3.pull-right
      .pull-right
        = link_to member_path(member.id), class: 'text-info' do
          = fa_icon 'eye fw', class: 'mr-2', 'data-toggle': 'tooltip', 'data-placement': 'top', title: t('.tooltip_view')
        = link_to edit_member_path(member.id), class: 'text-secondary' do
          = fa_icon 'edit', class: 'mr-2', 'data-toggle': 'tooltip', 'data-placement': 'top', title: t('.tooltip_edit')
        = link_to member_path(member.id), method: :delete, data: { confirm: t('.delete_confirmation') }, class: 'text-danger' do
          = fa_icon 'trash-o', class: 'mr-2', 'data-toggle': 'tooltip', 'data-placement': 'top', title: t('.tooltip_delete')

app/views/members/_personal_info_form.html.slim
#personal_info_form.card
  .card-header
    = fa_icon 'info fw', class: 'mr-2'
    = t('.section_title_personal_info')
  .card-body
    .row.justify-content-center
      .col-md-12
        .form-group.row
          = f.label :first_name, t('.label_first_name'), class: 'col-sm-3 col-form-label'
          .col-sm-9
            = f.text_field :first_name, class: 'form-control', required: true
        .form-group.row
          = f.label :fathers_last_name, t('.label_fathers_last_name'), class: 'col-sm-3 col-form-label'
          .col-sm-9
            = f.text_field :fathers_last_name, class: 'form-control', required: true
        .form-group.row
          = f.label :mothers_last_name, t('.label_mothers_last_name'), class: 'col-sm-3 col-form-label'
          .col-sm-9
            = f.text_field :mothers_last_name, class: 'form-control', required: true
        .form-group.row
          = f.label :major, t('.label_major'), class: 'col-sm-3 col-form-label'
          .col-sm-9
            = f.select :major, major_options, {}, class: 'form-control', required: true

app/views/members/_roborregos_info_form.html.slim
#roborregos_info_form.card.not-first-card
  .card-header
    = fa_icon 'sitemap fw', class: 'mr-2'
    = t('.section_title_roborregos')
  .card-body
    .row.justify-content-center
      .col-md-12
        .form-group.row
          = f.label :generation, t('.label_generation'), class: 'col-sm-3 col-form-label'
          .col-sm-9
            = f.text_field :generation, class: 'form-control', required: true
        .form-group.row
          = f.label :role, t('.label_role'), class: 'col-sm-3 col-form-label'
          .col-sm-9
            = f.select :role, role_options, {}, class: 'form-control', required: true
        .form-group.row
          = f.label :status, t('.label_status'), class: 'col-sm-3 col-form-label'
          .col-sm-9
            = f.select :status, status_options, {}, class: 'form-control', required: true
        .form-group.row
          = f.label :start_date, t('.label_start_date'), class: 'col-sm-3 col-form-label'
          .col-sm-9
            = f.date_field :start_date, class: 'form-control', required: true

app/views/members/edit.html.slim
header
  .title-row.row.align-items-center
    .col-12
      h1
        = fa_icon 'user fw', class: 'mr-2'
        = t('.title', member: @member.full_name)

#edit_member_section.content-section
  .row.justify-content-center
    .col-md-9
      = form_with model: @member, id: 'edit_member_form' do |f|
        = render partial: 'personal_info_form', locals: { f: f }
        = render partial: 'contact_info_form', locals: { f: f }
        = render partial: 'roborregos_info_form', locals: { f: f }

        .submit-member-form-section
          = f.submit t('.submit'), class: 'btn btn-success'
          = link_to t('.cancel'), member_path(id: @member.id), class: 'btn btn-danger ml-3'

app/views/members/index.html.slim
header
  .title-row.row.align-items-center
    .col-12
      h1
        = fa_icon 'users fw', class: 'mr-2'
        = t('.title')
  .nav-row.row.align-items-end.pb-2
    .col-2
    .col-8
      .dropdown
        a#sort_members_by.btn.btn-secondary.dropdown-toggle href='#' role='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='flase'
          = t('.sort_by')
        .dropdown-menu aria-labelledby='sort_members_by'
          = link_to members_path(sort_by: :role), class: 'dropdown-item' do
            = t('.sort_by_role')
          = link_to members_path(sort_by: :major), class: 'dropdown-item' do
            = t('.sort_by_major')
          = link_to members_path(sort_by: :status), class: 'dropdown-item' do
            = t('.sort_by_status')
          = link_to members_path(sort_by: :generation), class: 'dropdown-item' do
            = t('.sort_by_generation')
    .col-2
      = link_to new_member_path, class: 'btn btn-success' do
        = fa_icon 'user-plus', class: 'mr-2'
        = t('.register')

#members_list_section.content-section
  .row.justify-content-center
    .col-md-10
      #members_list.card
        ul.list-group.list-group-flush
          = render partial: 'member', collection: @members

app/views/members/new.html.slim
header
  .title-row.row.align-items-center
    .col-12
      h1
        = fa_icon 'user-plus fw', class: 'mr-2'
        = t('.title')

#new_member_section.content-section
  .row.justify-content-center
    .col-md-9
      = form_with model: @member, id: 'new_member_form' do |f|
        = render partial: 'personal_info_form', locals: { f: f }
        = render partial: 'contact_info_form', locals: { f: f }
        = render partial: 'roborregos_info_form', locals: { f: f }

        .submit-member-form-section
          = f.hidden_field :username
          = f.submit t('.submit'), class: 'btn btn-success'
          = link_to t('.cancel'), members_path, class: 'btn btn-danger ml-3'

app/views/members/show.html.slim
header
  .title-row.row.align-items-center
    .col-12
      h1
        = fa_icon 'user fw', class: 'mr-2'
        = @member.full_name

  .nav-row.row.align-items-end.pb-2
    .col-3
      = link_to members_path, class: 'btn btn-info' do
        = fa_icon 'angle-left', class: 'mr-2'
        = t('.return')
    .col-6
      = link_to edit_member_path(@member.id), class: 'btn btn-warning' do
        = fa_icon 'edit', class: 'mr-2'
        = t('.edit')
    .col-3
      = link_to member_path(@member.id), method: :delete, data: { confirm: t('.delete_confirmation') }, class: 'btn btn-danger' do
        = fa_icon 'trash-o', class: 'mr-2'
        = t('.delete')

#member_info_section.content-section
  .row.justify-content-center
    .col-md-10
      #contact_info.card
        .card-header
          = fa_icon 'address-book fw', class: 'mr-2'
          = t('.section_title_contact')
        ul.list-group.list-group-flush
          li.list-group-item
            .row
              .col-4.info-title
                = t('.label_email')
              .col-8
                = @member.email
          li.list-group-item
            .row
              .col-4.info-title
                = t('.label_github_username')
              .col-8
                = @member.github_username
          li.list-group-item
            .row
              .col-4.info-title
                = t('.label_linkedin_username')
              .col-8
                = @member.linkedin_username
          li.list-group-item
            .row
              .col-4.info-title
                = t('.label_description')
              .col-8
                = @member.description

      #roborregos_info.card.not-first-card
        .card-header
          = fa_icon 'sitemap fw', class: 'mr-2'
          = t('.section_title_roborregos')
        ul.list-group.list-group-flush
          li.list-group-item
            .row
              .col-4.info-title
                = t('.label_major')
              .col-8
                = @member.major
          li.list-group-item
            .row
              .col-4.info-title
                = t('.label_generation')
              .col-8
                = @member.generation
          li.list-group-item
            .row
              .col-4.info-title
                = t('.label_role')
              .col-8
                = @member.role
          li.list-group-item
            .row
              .col-4.info-title
                = t('.label_status')
              .col-8
                = @member.status
          li.list-group-item
            .row
              .col-4.info-title
                = t('.label_start_date')
              .col-8
                = @member.start_date.to_date.to_s(:long)